# permissions for end users to edit wavefrontproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wavefrontproxy-editor-role
rules:
- apiGroups:
  - wavefrontproxy.wavefront.com
  resources:
  - wavefrontproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wavefrontproxy.wavefront.com
  resources:
  - wavefrontproxies/status
  verbs:
  - get
